apiVersion: v1
kind: Service
metadata:
  name: kube-tp1-nginx-service
  labels:
    app: kube-tp1
    tier: frontend
spec:
  selector:
    app: kube-tp1
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
